spring.application.name=PASiR_Sommer_Bartosz

# Blokujemy import z .env na wypadek gdyby tam coś psuło
# spring.config.import=optional:file:.env[.properties]

# MySQL Configuration (Używamy portu 3306 i małych liter)
spring.datasource.url=jdbc:mysql://127.0.0.1:3307/sommer_bartosz_gi_spring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=user-bs
spring.datasource.password=Maciej27!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Sztywne wymuszenie dialektu w pliku konfiguracyjnym
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#GraphQL
spring.graphql.http.path=/graphql
spring.graphql.schema.file-extensions=.graphql,.graphqls,.gqls
JWT_SECRET=mojaMegaBezpiecznaTajnaSekretnaFrazaDoJwtTokenow1234567890ABCDEF!BartSommer